### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by bluzarraga**

### CODE REVIEW

**Review by cheewaio — COMMENTED** [review]
shouldn't the image be using digest instead of tag?

**Comment by bluzarraga** [comment]
When I made the change, it was setup as an if/else depending on whether the digest was defined, otherwise it would use the tag so I included the tag in the manifest. If we are never going to use the tag now, then I will just remove the tag and leave it as strictly digest.

**Comment by cheewaio** [comment]
when we release, we will only use digest .. tag may only be used in development only.
so i think u can only consider digest ..thanks

**Review by cheewaio — APPROVED** [review]
/lgtm

**Pull request merged**
